spring:
  config:
    import: env.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB.URL:localhost}:3306/${DB.NAME:moiza}
    username: ${DB.USERNAME:root}
    password: ${DB.PASSWORD:1111}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: ${DB.DDL:validate}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
      password: ${REDIS.PASSWORD}

jwt:
  access-time: 3600000 # 1시간
  refresh-time: 2592000000 # 30일
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT.SECRET}

auth:
  google:
    base-url: ${GOOGLE.BASE.URL}
    client-id: ${GOOGLE.CLIENT}
    redirect-url: ${GOOGLE.REDIRECT}

nextcloud:
  base-url: ${NEXTCLOUD.BASE.URL}
  username: ${NEXTCLOUD.USERNAME}
  password: ${NEXTCLOUD.PASSWORD}
